# DEV - Environment used by developers.,

server:
  port: 1234
  
spring:
  main:
    banner-mode: console
  application:
    name: Ataulfo 
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
#    url: jdbc:mysql://localhost:3306/ataulfodb
    url: jdbc:mysql://localhost:3306/vasudb?createDatabaseIfNotExist=true
    username: ${DbName}
    password: ${Password}
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: update
  
  
