server:
  port: 1234
  
spring:
  main:
    banner-mode: console
  application:
    name: Ataulfo 
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://localhost:3306/ataulfo?createDatabaseIfNotExist=true
    username: root
    password: boss
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: update
  
  
